create table person(
                       id int generated by default as identity primary key ,
                       name varchar not null,
                       age int check ( age > 0 ),
                       email varchar unique
);

create table "order"
(
    id int generated by default as identity primary key ,
    name varchar not null,
    person_id int references person(id)
);

select * from person left join "order" on person.id = "order".person_id

select person.name, "order".name from person left join "order"  on person.id = "order".person_id

select person.id, "order".id from person left join "order" on person.id = "order".person_id

select person.email, "order".name from person join "order" on person.id = "order".person_id

select "order".name from person join "order" on person.id = "order".person_id where person.name = 'Airat'

select "order".name from person join "order" on person.id = "order".person_id where person.age = 32

insert into "order"( name, person_id) values ('TV', 1);
insert into "order"( name, person_id) values ('Car', 2);
insert into "order"( name, person_id) values ('Iphone', 3);
insert into "order"( name, person_id) values ('Boombox', 4);
insert into "order"( name, person_id) values ('Ipod', 3);

drop table person
select * from person;

select name
from person where age = 32;

select name from person;
insert into person( name, age, email) values ('Viktor',32, 'viktor@mail.ru');
insert into person( name, age, email) values ( 'Damir', 17, 'damir@mail.ru');
insert into person( name, age, email) values ( 'Airat', 25, 'airat@mail.ru');
insert into person( name, age, email) values ( 'Maxim', 32, 'maxim@mail.ru');
insert into person( name, age, email) values ( 'Tagir', 25, 'tagir@mail.ru');
update person set name='Viktor32' where name='Viktor' and age=32;
delete from person where name='Viktor32';
drop table person;

create table person(
                       id int,
                       name varchar,
                       age int
);

select * from person where name='Damir'

insert into person(name, age) values ('Viktor', 32)

select * from person;

update person set id=5 where name='Viktor' and age=32

update person
set name = '', age = 1, email = ''
where id = 1;

update person set name = 'Viktor', age = 32, email = 'viktor@gmail.com'  where id = 5

delete from person where id = 5
delete from person where id = 5

delete from person where age = 32
insert into person(id, name, age) values (4, 'Maxim', 32);

create table book(
                     id int,
                     name varchar,
                     dateOfIssue int
)

drop table book

create table picture(
                        id int,
                        name varchar,
                        author varchar
)

insert into picture(id, name, author) values (1, '9 val', 'Aivazoskiy')

select *
from picture;

drop table picture

create table tales(
                      id int,
                      name varchar,
                      author varchar,
                      yearOfIssue int
)

insert into tales(id, name, author, yearOfIssue) VALUES (1, 'kolobok', 'narodnaya', 1913)

select *
from tales;




create sequence my_seq

select nextval('my_seq')





